name: Java CI with Maven & Cucumber

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run automated tests
      run: mvn clean verify

    - name: Upload Test Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-test-reports
        path: target/cucumber-report-html/
        retention-days: 7
